### ISSUE TITLE
Create UML diagrams

### ISSUE THREAD

**Issue by nklapste** [CMPUT301F18T16/Baudit#17]
UML diagrams for Baudit need to be created and maintained.

They "should" follow the syntax followed within CMPUT 301.

They should be placed within the `/doc/uml` directory.

Maybe we should use UML generation tools such as IDEA Ultimate's built-in UML generation or simpleUML (Jetbrains IDE plugin).
Doing this manually seems archaic.

**Comment by nklapste** [comment]
@wlt30 are these diagrams now done and placed in master's `/doc/uml`?

Can I close this issue?

**Comment by wlt30** [comment]
Hey Nathan, 

Sorry, I haven't gone any further with the UML diagram. I'll be working on the storyboard and mockup with Thomas.
