### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by nklapste** [CMPUT301F18T16/Baudit#52]
Define any special terminology in the application domain (i.e., not programming terms). 
Terms should be described in the context related to Baudit.

Glossary should contain citations where applicable.

The glossary should contain definitions of important terms used in your requirements specification and application, that come from the problem domain. For example, if your app will have "users" you should define what a "user" is.

The glossary entries should specify relevant sources. For example, your definition of "user" should come from some external source, such as a reference (e.g. a dictionary) or well-known technology (e.g. amazon.com) that defines the term and that external source should not be discussing drug users, because that would be irrelevant to the domain of your app.

Related page:
https://github.com/CMPUT301F18T16/Baudit/wiki/Glossary

Related to #34

**Comment by nklapste** [comment]
@jalqueza please go through the glossary and add citations to the medical terms added.

**Comment by nklapste** [comment]
@jalqueza please fill in the terms with TODO under them within the context of usage of the Baudit app

**Comment by jalqueza** [comment]
@nklapste  

Whats the difference between these three: Medical Problem List, Medical Problem Record, Medical Problem Record List? 

I made some assumptions and updated the glossary

**Comment by nklapste** [comment]
@jalqueza 

A `medical problem` is the initial item a patient can create

A `medical problem record` is an item a patient or care provider can attach onto a medical problem. They describe details, photos, comments, and/or progress of the medical problem.

They both have lists as their must be multiples of them.
